/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import forms.LoginUsuario;
import dao.DadosUsuario;
import beans.Usuario;
import dao.UsuarioDAO;
import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.Timer;
import criptor.Criptografia;
import javax.swing.JOptionPane;

/**
 *
 * @author anton
 */
public class CadastroUsuario extends javax.swing.JFrame {

    Usuario usuario = new Usuario();
    DadosUsuario dado = new DadosUsuario();
    
    private Timer timer;
    boolean mostrando = false;
    private String numero;
    
    /**
     * Creates new form CadastroUsuario
     */
    
    ButtonGroup grupoNivelAcesso = new ButtonGroup();
    
    public CadastroUsuario(int  idUsuario) {
        initComponents();
        
        grupoNivelAcesso.add(gerente);
        grupoNivelAcesso.add(funcionario);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        erro1 = new javax.swing.JLabel();
        txtSobreNome = new javax.swing.JTextField();
        erro2 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        erro3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        erro4 = new javax.swing.JLabel();
        PSenha = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        erro5 = new javax.swing.JLabel();
        gerente = new javax.swing.JRadioButton();
        funcionario = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        mostra = new javax.swing.JButton();
        erro6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Cadastro de Usuarios");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nome");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Sobrenome");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CPF");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Email");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Senha");

        erro1.setForeground(new java.awt.Color(0, 0, 0));

        erro2.setForeground(new java.awt.Color(0, 0, 0));

        erro3.setForeground(new java.awt.Color(0, 0, 0));

        erro4.setForeground(new java.awt.Color(0, 0, 0));

        PSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PSenhaKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        erro5.setForeground(new java.awt.Color(0, 0, 0));

        gerente.setForeground(new java.awt.Color(0, 0, 0));
        gerente.setText("Gerente");

        funcionario.setForeground(new java.awt.Color(0, 0, 0));
        funcionario.setText("Funcionario(a)");

        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        mostra.setBackground(new java.awt.Color(0, 0, 0));
        mostra.setForeground(new java.awt.Color(255, 255, 255));
        mostra.setText("mostra senha");
        mostra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostraActionPerformed(evt);
            }
        });

        jButton5.setText("Login");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(111, 111, 111))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(funcionario))
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtNome)
                    .addComponent(erro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSobreNome)
                    .addComponent(erro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCPF)
                    .addComponent(erro3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail)
                    .addComponent(erro4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(erro5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(erro6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erro1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSobreNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erro2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erro3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erro4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mostra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(erro5, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gerente)
                    .addComponent(funcionario))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(erro6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       txtCPF.setText("");
       txtEmail.setText("");
       txtNome.setText("");
       txtSobreNome.setText("");
       PSenha.setText("");
       
       grupoNivelAcesso.clearSelection();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mostraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostraActionPerformed
        
       
        if(mostrando) {
            PSenha.setEchoChar('*');
            mostrando = false;
        } else {
            PSenha.setEchoChar((char) 0);
            mostrando = true;
        }
       
    }//GEN-LAST:event_mostraActionPerformed

    private void PSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PSenhaKeyTyped
        PSenha.setEchoChar((char) 0);
        
        if(timer != null && timer.isRunning()) {
            timer.stop();
        }
        
        timer = new Timer(1000, e -> {
           PSenha.setEchoChar('*');
           timer.stop();
        });
        
        timer.setRepeats(false);
        timer.start();
        
    }//GEN-LAST:event_PSenhaKeyTyped

    public String limpar (String cpf) {
        return cpf.replaceAll("[^0-9]", "");
    }
    
    public int calculoDigito(String num, int[] peso) {
        int soma = 0;
        
        for(int i = 0; i < peso.length; i++) {
            soma += Character.getNumericValue(num.charAt(i)) * peso[i];
        }
        
        int resto = soma % 11;
        
        return (resto < 2) ? 0 : (11 - resto);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String strNome = txtNome.getText();
        String strSobrenome = txtSobreNome.getText();
        String strCPF = txtCPF.getText();
        String strEmail = txtEmail.getText();
        char[] strSenha = PSenha.getPassword();
        
        boolean validEmail = false, validSenha = false, validCPF = false; 
        
        if(strNome == null || strNome.equals("")) {
            erro1.setText("Nome vazio preenchar o campo");
            erro1.setForeground(Color.red);
        } else {
            erro1.setText("Campo valido!");
            erro1.setForeground(Color.black);
            usuario.setNome(strNome);
        }
        
        if(strSobrenome == null || strSobrenome.equals("")) {
            erro2.setText("Prenchar o campo vazio");
            erro2.setForeground(Color.red);
        } else {
            erro2.setText("Campo valido!");
            erro2.setForeground(Color.black);
            usuario.setSobrenome(strSobrenome);
        }
        
        if(strCPF == null || strCPF.trim().isEmpty()) {
            erro3.setText("Campo vazio preencha o campo");
            erro3.setForeground(Color.red);
        } else {
            numero = limpar(strCPF);
            
            if(numero.length() != 11 || numero.matches("(\\d)\\1{10}")) {
                erro3.setText("CPF invalido");
                erro3.setForeground(Color.red);
                
            } else {
                int[] peso1 = {10, 9, 8, 7, 6, 5, 4, 3, 2};
                int[] peso2 = {11, 10, 9, 8, 7, 6, 5, 4, 3, 2};
                
                int primeiroDigito = calculoDigito(numero.substring(0, 9), peso1);
                int segundoDigito = calculoDigito(numero.substring(0, 9) + primeiroDigito, peso2);

                String cpfCalculado = numero.substring(0, 9) + primeiroDigito + segundoDigito;
                
                if(numero.equals(cpfCalculado)) {
                    erro3.setText("CPF valido");
                    erro3.setForeground(Color.black);
                    usuario.setCpf(strCPF);
                    validCPF = true;
                } else {
                    erro3.setText("CPF invalido");
                    erro3.setForeground(Color.red);
                }
                
            }
            
        }
        
        if(strEmail == null || strEmail.trim().isEmpty()) {
            erro4.setText("Email vazio preenchar o campo");
            erro4.setForeground(Color.red);
        } else {
            if(strEmail.contains("@")) {
                erro4.setText("Email valido!");
                erro4.setForeground(Color.black);
                usuario.setEmail(strEmail);
                validEmail = true;
            } else {
                erro4.setText("Prenchar com o @");
                erro4.setForeground(Color.red);
            }
        }
        
        if(strSenha.length == 0) {
            erro5.setText("Campo vazio preencha ");
            erro5.setForeground(Color.red);
        } else {
            if(strSenha.length < 8) {
                erro5.setText("Senha muito fraca tente outra");
                erro5.setForeground(Color.red);
            } else {
                boolean letraMaiuscula = false; // validar letras Maiusculas
                boolean letraMinuscula = false; // validar letras Minusculas
                boolean caracterEspecial = false; // validar caracteres especiais
                boolean digito = false; // validar digitos
                
                for(char c : strSenha) {
                    if(Character.isUpperCase(c)) { // validando se tem letra maiusculas
                        letraMaiuscula = true;
                    } else if(Character.isLowerCase(c)) { // validando se tem letras minusculas
                        letraMinuscula = true;
                    } else if(Character.isDigit(c)) { // validando se tem digito
                        digito = true;
                    } else if(!Character.isLetterOrDigit(c)) { // validando se tem caracter especial por exemplo @
                        caracterEspecial = true;
                    }
                }
                
                // Se tudo é verdadeiro então a senha é valida se não a senha e invalida
                if(letraMaiuscula == true || letraMinuscula == true || digito == true || caracterEspecial == true ) {
                    erro5.setText("Senha valida");
                    erro5.setForeground(Color.black);
                    usuario.setSenha(new String(Criptografia.getSHA256(new String(strSenha))));
                    validSenha = true;
                } else {
                    erro5.setText("Senha invalida");
                    erro5.setForeground(Color.red);
                }
                
                 // vai dizer o nivel de segurança da senha
                if(letraMaiuscula == true && letraMinuscula == true && digito == true && caracterEspecial == true ) {
                    erro5.setText("Senha forte");
                    erro5.setForeground(Color.black);
                }else if((letraMaiuscula == true && letraMinuscula == true) || (digito == true && caracterEspecial == true) || (digito == true && letraMinuscula == true) || (digito == true && letraMaiuscula == true) || (caracterEspecial == true && letraMinuscula == true) || (caracterEspecial == true && letraMaiuscula == true)) {
                    erro5.setText("Senha intermediaria");
                    erro5.setForeground(Color.black);
                } else if(letraMaiuscula == true || letraMinuscula == true || digito == true || caracterEspecial == true) {
                    erro5.setText("Senha fraca");
                    erro5.setForeground(Color.black);
                    
                }
                
            }
        }
        
        if(gerente.isSelected()) {
            usuario.setTipoFuncionario("Gerente"); 
        } else {
            usuario.setTipoFuncionario("Funcionario");
        }
        
        if(validCPF == true && validEmail == true && validSenha == true) {
            DadosUsuario.Adicionar(usuario);
            
            try {
                UsuarioDAO usuarioDao = new UsuarioDAO();
                
                usuarioDao.cadastra(usuario);
                
                JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
                
                new LoginUsuario(usuario.getId()).setVisible(true);
                
            } catch (Exception e) {
            }
            
        }
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Usuario usuario = new Usuario();
        
        new LoginUsuario(usuario.getId()).setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PSenha;
    private javax.swing.JLabel erro1;
    private javax.swing.JLabel erro2;
    private javax.swing.JLabel erro3;
    private javax.swing.JLabel erro4;
    private javax.swing.JLabel erro5;
    private javax.swing.JLabel erro6;
    private javax.swing.JRadioButton funcionario;
    private javax.swing.JRadioButton gerente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mostra;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSobreNome;
    // End of variables declaration//GEN-END:variables
}
