package forms;

import forms.Home;
import dao.DadosProduto;
import beans.Usuario;
import beans.produtos;
import dao.ProdutoDAO;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author anton
 */
public class Categorias extends javax.swing.JFrame {

    /**
     * Creates new form Categorias
     */
    
    List<String> categoriaRacao = new ArrayList<>();
    List<String> categoriaRemedio = new ArrayList<>();
    List<String> categoriaBanho = new ArrayList<>();
    List<String> categoriaAcessorios = new ArrayList<>();
    List<String> categoriaOutros = new ArrayList<>();
    
    public Categorias() {
        initComponents();
        AmazenarEmCadaCategoria();
        PreencherOsComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbRacao = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbRemedio = new javax.swing.JComboBox<>();
        cbbanho = new javax.swing.JComboBox<>();
        cbAcessorios = new javax.swing.JComboBox<>();
        cbOutros = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbRacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Categorias");

        jLabel2.setText("Ração");

        cbRemedio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        cbbanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel3.setText("Remedio");

        jLabel4.setText("Banho");

        jLabel5.setText("Acessorios");

        jLabel6.setText("Outros");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(cbRacao, 0, 539, Short.MAX_VALUE)
                    .addComponent(cbRemedio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbanho, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbAcessorios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbOutros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbbanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbAcessorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbOutros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Usuario usuario = new Usuario();
        
        new Home(usuario.getId()).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void AmazenarEmCadaCategoria() {
        
        ProdutoDAO produtoDao = new ProdutoDAO();
        
        List<produtos> listarProduto = produtoDao.listar();
        
        for(produtos p : listarProduto) {
            if((    p.getNome().contains("Ração") || 
                    p.getNome().contains("Racao") || 
                    p.getNome().contains("racão") || 
                    p.getNome().contains("racao")) ||
                    p.getNome().contains("Petisco") ||
                    p.getNome().contains("petisco")) {
                
                categoriaRacao.add(p.getNome() + " " + p.getQuantidade() + " " + p.getValor());
            
            } else if(( p.getNome().contains("remedio") || 
                        p.getNome().contains("remédio")) || 
                        p.getNome().contains("Remedio") ||
                        p.getNome().contains("Remédio") || (
                        p.getNome().contains("vermifugo") || 
                        p.getNome().contains("vermífugo")) || 
                        p.getNome().contains("antipulgas")) {
                
                categoriaRemedio.add(p.getNome() + " " + p.getQuantidade() + " " + p.getValor());
            
            } else if(  p.getNome().contains("shampoo") ||
                        p.getNome().contains("Shampoo") ||
                        p.getNome().contains("Sabonete") ||
                        p.getNome().contains("sabonete") ||
                        p.getNome().contains("Perfume") ||
                        p.getNome().contains("perfume") ||
                        p.getNome().contains("Higiene") ||
                        p.getNome().contains("higiene")) {
                
                categoriaBanho.add(p.getNome() + " " + p.getQuantidade() + " " + p.getValor());
            
            } else if(  p.getNome().contains("coleira") ||
                        p.getNome().contains("Coleira") ||
                        p.getNome().contains("Guia") ||
                        p.getNome().contains("guia") ||
                        p.getNome().contains("Roupa") ||
                        p.getNome().contains("roupa") ||
                        p.getNome().contains("Cama") ||
                        p.getNome().contains("cama")) {
                
                categoriaAcessorios.add(p.getNome() + " " + p.getQuantidade() + " " + p.getValor());
            
            } else {
                categoriaOutros.add(p.getNome() + " " + p.getQuantidade() + " " + p.getValor());
            }
        }
    }
    
    private void PreencherOsComboBox() {
    
        for(String p : categoriaRacao) {
            cbRacao.addItem(p.toString());
        }
        
        for(String p : categoriaRemedio) {
            cbRemedio.addItem(p.toString());
        }
        
        for(String p : categoriaBanho) {
            cbbanho.addItem(p.toString());
        }
        
        for(String p : categoriaAcessorios) {
            cbAcessorios.addItem(p.toString());
        }
        
        for(String p : categoriaOutros) {
            cbOutros.addItem(p.toString());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbAcessorios;
    private javax.swing.JComboBox<String> cbOutros;
    private javax.swing.JComboBox<String> cbRacao;
    private javax.swing.JComboBox<String> cbRemedio;
    private javax.swing.JComboBox<String> cbbanho;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
